# Generated by Django 4.0.4 on 2025-01-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=30)),
                ('dev_last_name', models.CharField(max_length=30)),
                ('dev_nickname', models.CharField(max_length=30)),
                ('dev_years', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=30)),
                ('enterprise_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_star', models.IntegerField(choices=[(1, 'MUITO RUIM'), (2, 'RUIM'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')])),
                ('title_game', models.CharField(max_length=30)),
                ('year_game', models.PositiveIntegerField()),
                ('devs_game', models.ManyToManyField(to='games.dev')),
                ('enterprise_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=30)),
                ('publisher_year', models.PositiveIntegerField()),
                ('enterprise_pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.enterprise')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='game',
            name='publisher_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.publisher'),
        ),
        migrations.AddField(
            model_name='dev',
            name='enterprises',
            field=models.ManyToManyField(to='games.enterprise'),
        ),
    ]
