# Generated by Django 4.0.4 on 2025-01-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_dev_enterprise_game_publisher_delete_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description_game',
            field=models.TextField(blank=True, null=True),
        ),
    ]
